language: java
script:
 - mvn clean install
 deploy:   provider: heroku
             api_key:
             secure: $HEROKU_API_KEY
             app: ncproject
               on:
                 branch: master